### ISSUE TITLE
docker-compose builds fails due to 'wal-e < v1.0.0' floating version dependency on 'azure >= 0.7.0' (due to 'azure >= 5.0.0' meta package deprecation)

### ISSUE THREAD

**Issue by seanpianka** [mattermost/mattermost#14289]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
`$ docker-compose build` fails building `db` due to a Python dependency issue (azure 5+).

#### Steps to reproduce
Using commit `1bfa69db5c0c1f36d6f65e57469c3fea0ecb3763`:
```
$ git clone https://github.com/mattermost/mattermost-docker.git
$ cd mattermost-docker
$ docker-compose build
```

#### Expected behavior
`db` image should be successfully built.

#### Observed behavior (that appears unintentional) 
```
lab@blackbox:~/mattermost-docker$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
lab@blackbox:~/mattermost-docker$ ls -l
total 52K
drwxrwxr-x 2 lab 4.0K Apr 13 12:54 app
drwxrwxr-x 5 lab 4.0K Apr 13 12:54 contrib
-rwxrwxr-x 1 lab  609 Apr 13 12:54 CONTRIBUTING.md
drwxrwxr-x 2 lab 4.0K Apr 13 12:54 db
-rwxrwxr-x 1 lab 2.0K Apr 13 12:54 docker-compose.yml
-rw-rw-r-- 1 lab  10K Apr 13 12:54 LICENSE
-rw-rw-r-- 1 lab 2.8K Apr 13 12:54 MAINTENANCE.md
-rw-rw-r-- 1 lab 9.3K Apr 13 12:54 README.md
drwxrwxr-x 2 lab 4.0K Apr 13 12:54 web
lab@blackbox:~/mattermost-docker$ docker-compose build
Building web
Step 1/8 : FROM nginx:mainline-alpine
 ---> 377c0837328f
Step 2/8 : RUN rm /etc/nginx/conf.d/default.conf     && apk add --no-cache curl
 ---> Using cache
 ---> 7c23c6cf8247
Step 3/8 : COPY ["./mattermost", "./mattermost-ssl", "/etc/nginx/sites-available/"]
 ---> Using cache
 ---> c69de103bfe5
Step 4/8 : COPY ./security.conf /etc/nginx/conf.d/
 ---> Using cache
 ---> bbab6904def8
Step 5/8 : COPY entrypoint.sh /
 ---> Using cache
 ---> 9c9f344874b7
Step 6/8 : HEALTHCHECK CMD curl --fail http://localhost:80 || exit 1
 ---> Using cache
 ---> 930e91a6afb4
Step 7/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 8695d0193a86
Step 8/8 : VOLUME ["/var/run", "/etc/nginx/conf.d/", "/var/cache/nginx/"]
 ---> Using cache
 ---> dda726e3db81
Successfully built dda726e3db81
Successfully tagged mattermostdocker_web:latest
Building app
Step 1/17 : FROM alpine:3.10
 ---> af341ccd2df8
Step 2/17 : ENV PATH="/mattermost/bin:${PATH}"
 ---> Using cache
 ---> 6b8817059e65
Step 3/17 : ENV MM_VERSION=5.21.0
 ---> Using cache
 ---> ecce831d47fb
Step 4/17 : ARG edition=enterprise
 ---> Using cache
 ---> 2590a5500f3b
Step 5/17 : ARG PUID=2000
 ---> Using cache
 ---> da0beb94c8b8
Step 6/17 : ARG PGID=2000
 ---> Using cache
 ---> 39885749335b
Step 7/17 : ARG MM_BINARY=
 ---> Using cache
 ---> 330b3d20d72e
Step 8/17 : RUN apk add --no-cache 	ca-certificates 	curl 	jq 	libc6-compat 	libffi-dev     libcap 	linux-headers 	mailcap 	netcat-openbsd 	xmlsec-dev 	tzdata && rm -rf /tmp/*
 ---> Using cache
 ---> 1ee4adc785a9
Step 9/17 : RUN mkdir -p /mattermost/data /mattermost/plugins /mattermost/client/plugins     && if [ ! -z "$MM_BINARY" ]; then curl $MM_BINARY | tar -xvz ;       elif [ "$edition" = "team" ] ; then curl https://releases.mattermost.com/$MM_VERSION/mattermost-team-$MM_VERSION-linux-amd64.tar.gz | tar -xvz ;       else curl https://releases.mattermost.com/$MM_VERSION/mattermost-$MM_VERSION-linux-amd64.tar.gz | tar -xvz ; fi     && cp /mattermost/config/config.json /config.json.save     && rm -rf /mattermost/config/config.json     && addgroup -g ${PGID} mattermost     && adduser -D -u ${PUID} -G mattermost -h /mattermost -D mattermost     && chown -R mattermost:mattermost /mattermost /config.json.save /mattermost/plugins /mattermost/client/plugins     && setcap cap_net_bind_service=+ep /mattermost/bin/mattermost
 ---> Using cache
 ---> 4e4177dfab12
Step 10/17 : USER mattermost
 ---> Using cache
 ---> 143f18bbb99e
Step 11/17 : HEALTHCHECK CMD curl --fail http://localhost:8000 || exit 1
 ---> Using cache
 ---> 58e10eba48fa
Step 12/17 : COPY entrypoint.sh /
 ---> Using cache
 ---> 37847bef5a56
Step 13/17 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d073db5df60e
Step 14/17 : WORKDIR /mattermost
 ---> Using cache
 ---> 504258fb573c
Step 15/17 : CMD ["mattermost"]
 ---> Using cache
 ---> 796fdd1c7ad6
Step 16/17 : EXPOSE 8000
 ---> Using cache
 ---> 0aabd98af409
Step 17/17 : VOLUME ["/mattermost/data", "/mattermost/logs", "/mattermost/config", "/mattermost/plugins", "/mattermost/client/plugins"]
 ---> Using cache
 ---> b8eab18ab09d
Successfully built b8eab18ab09d
Successfully tagged mattermostdocker_app:latest
Building db
Step 1/9 : FROM postgres:9.4-alpine
 ---> 4e66908aa630
Step 2/9 : ENV DEFAULT_TIMEZONE UTC
 ---> Using cache
 ---> 5b98186271e4
Step 3/9 : RUN apk add --no-cache       build-base       curl       libc6-compat       libffi-dev       linux-headers       python-dev       py-pip       py-cryptography       pv       libressl-dev     && pip --no-cache-dir install 'wal-e<1.0.0' envdir     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*
 ---> Running in 8786e763cd18
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/49) Upgrading musl (1.1.24-r0 -> 1.1.24-r2)
(2/49) Installing libgcc (9.2.0-r4)
(3/49) Installing libstdc++ (9.2.0-r4)
(4/49) Installing binutils (2.33.1-r0)
(5/49) Installing libmagic (5.37-r1)
(6/49) Installing file (5.37-r1)
(7/49) Installing gmp (6.1.2-r1)
(8/49) Installing isl (0.18-r0)
(9/49) Installing libgomp (9.2.0-r4)
(10/49) Installing libatomic (9.2.0-r4)
(11/49) Installing mpfr4 (4.0.2-r1)
(12/49) Installing mpc1 (1.1.0-r1)
(13/49) Installing gcc (9.2.0-r4)
(14/49) Installing musl-dev (1.1.24-r2)
(15/49) Installing libc-dev (0.7.2-r0)
(16/49) Installing g++ (9.2.0-r4)
(17/49) Installing make (4.2.1-r2)
(18/49) Installing fortify-headers (1.1-r0)
(19/49) Installing build-base (0.5-r1)
(20/49) Installing ca-certificates (20191127-r1)
(21/49) Installing nghttp2-libs (1.40.0-r0)
(22/49) Installing libcurl (7.67.0-r0)
(23/49) Installing curl (7.67.0-r0)
(24/49) Installing libc6-compat (1.1.24-r2)
(25/49) Installing linux-headers (4.19.36-r0)
(26/49) Installing libffi (3.2.1-r6)
(27/49) Installing pkgconf (1.6.3-r0)
(28/49) Installing libffi-dev (3.2.1-r6)
(29/49) Installing libressl3.0-libcrypto (3.0.2-r0)
(30/49) Installing libressl3.0-libssl (3.0.2-r0)
(31/49) Installing libressl3.0-libtls (3.0.2-r0)
(32/49) Installing libressl-dev (3.0.2-r0)
(33/49) Installing pv (1.6.6-r1)
(34/49) Installing libbz2 (1.0.8-r1)
(35/49) Installing expat (2.2.9-r1)
(36/49) Installing gdbm (1.13-r1)
(37/49) Installing sqlite-libs (3.30.1-r1)
(38/49) Installing python3 (3.8.2-r0)
(39/49) Installing py3-cparser (2.19-r4)
(40/49) Installing py3-cffi (1.13.2-r0)
(41/49) Installing py3-idna (2.8-r3)
(42/49) Installing py3-asn1crypto (1.2.0-r1)
(43/49) Installing py3-six (1.13.0-r0)
(44/49) Installing py3-cryptography (2.8-r1)
(45/49) Installing python2 (2.7.16-r3)
(46/49) Installing py-setuptools (42.0.2-r0)
(47/49) Installing py3-setuptools (42.0.2-r0)
(48/49) Installing py2-pip (18.1-r0)
(49/49) Installing python2-dev (2.7.16-r3)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 349 MiB in 77 packages
Collecting wal-e<1.0.0
  Downloading https://files.pythonhosted.org/packages/7a/67/4da340652303e3adb26f6e9aa97b2118dbe5cd17be87e8a21dff9e9bc507/wal-e-0.9.2.tar.gz (100kB)
Collecting envdir
  Downloading https://files.pythonhosted.org/packages/75/dd/817dc77edf4807fc2c29e28046ab83aa7ccfe27e79d24ca37d7aaa1e36bb/envdir-1.0.1-py2.py3-none-any.whl
Collecting gevent>=1.0.2 (from wal-e<1.0.0)
  Downloading https://files.pythonhosted.org/packages/5a/79/2c63d385d017b5dd7d70983a463dfd25befae70c824fedb857df6e72eff2/gevent-1.5.0.tar.gz (5.3MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Collecting boto>=2.24.0 (from wal-e<1.0.0)
  Downloading https://files.pythonhosted.org/packages/23/10/c0b78c27298029e4454a472a1919bde20cb182dab1662cec7f2ca1dcc523/boto-2.49.0-py2.py3-none-any.whl (1.4MB)
Collecting azure>=0.7.0 (from wal-e<1.0.0)
  Downloading https://files.pythonhosted.org/packages/e8/48/ef73d5e71ecb84cacaeaf533f519be81825ad6198acc41bd821f440e7f7c/azure-5.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-A6m8WI/azure/setup.py", line 60, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
    -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
    -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
    -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
    -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts

    A more comprehensive discussion of the rationale for this decision can be found in the following issue:
    https://github.com/Azure/azure-sdk-for-python/issues/10646



    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-A6m8WI/azure/
ERROR: Service 'db' failed to build: The command '/bin/sh -c apk add --no-cache       build-base       curl       libc6-compat       libffi-dev       linux-headers       python-dev       py-pip       py-cryptography       pv       libressl-dev     && pip --no-cache-dir install 'wal-e<1.0.0' envdir     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*' returned a non-zero code: 1
```

#### Possible fixes
    Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
    -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
    -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
    -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
    -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts

    A more comprehensive discussion of the rationale for this decision can be found in the following issue:
    https://github.com/Azure/azure-sdk-for-python/issues/10646

**Comment by ahmaddanialmohd** [comment]
Hello, @seanpianka 

I believe that the issue that you facing here is related to https://github.com/mattermost/mattermost-docker/issues/463 Can you please confirm if the suggestions help you to fix the issue?
* [Suggestion #1](https://github.com/mattermost/mattermost-docker/issues/463#issuecomment-611688935)
* [Suggestion #2](https://github.com/mattermost/mattermost-docker/issues/463#issuecomment-612962185)

**Comment by lieut-data** [comment]
Thanks for reporting this issue and for the community discussion around it. After multiple years of inactivity, we're closing this to help keep our issue tracker focused on active work. If this is still relevant, please feel free to open a new issue with updated context and we'll be happy to take another look.
