### ISSUE TITLE
[Bug] Cannot create slash command

### ISSUE THREAD

**Issue by BigMakCode** [mattermost/mattermost#24024]
#### Summary
Can't create slash command after update version 7=>8 - white window and no more.

#### Steps to reproduce
Open Integrations - Slash commands - Create - See white window

#### Expected behavior
Show create slash command window

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/81349914/d642b84e-b404-4bc6-94c3-d5773adbfdb9)
![image](https://github.com/mattermost/mattermost/assets/81349914/b19d422d-c015-4b24-8440-16cc7fd43bcf)
```JavaScript Console Error
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at p (utils.js:76:15)
    at ct (message.js:31:5)
    at wt (provider.js:46:18)
    at Wt (message.js:21:17)
    at ao (react-dom.production.min.js:157:137)
    at $u (react-dom.production.min.js:267:460)
    at Ni (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at Ci (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
```

#### Possible fixes
Reload page, restart application

Current version is 8.0.0 (master/Tue Jul 11 13:17:40 UTC 2023) (Docker mattermost/mattermost-enterprise-edition:master)

**Comment by amyblais** [comment]
@BigMakCode I wasn't able to reproduce this - what OS and version are you on? Do you see errors in the Mattermost server logs?

**Comment by BigMakCode** [comment]
OS Windows 11 Pro 22H2 22621.1992
Browser Version 111.0.5563.64 (Official Build) (64-bit)
Server version 8.0.0 (master/Tue Jul 11 13:17:40 UTC 2023) (Docker mattermost/mattermost-enterprise-edition:master)

Server logs is clear (log level: debug)
```
debug [2023-07-13 17:45:25.654 Z] Received HTTP request caller="web/handlers.go:163" method=POST url=/api/v4/channels/members/me/view request_id=xhnxrkrhffd9bgcfxyhsd9q8ha status_code=200
debug [2023-07-13 17:45:25.657 Z] Received HTTP request caller="web/handlers.go:163" method=POST url=/api/v4/channels/members/me/view request_id=oaninnpixfnuzpho3hskmfiero status_code=200
debug [2023-07-13 17:45:25.671 Z] Received HTTP request caller="web/handlers.go:163" method=POST url=/api/v4/channels/members/me/view request_id=t4rixi61t3gwbfwyuaiohiaf6r status_code=200
debug [2023-07-13 17:45:25.711 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks user_id=myUserId request_id=rtscs7x3pb8j3q3hjiwru66zuc user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.718 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks user_id=myUserId request_id=rtscs7x3pb8j3q3hjiwru66zuc user_agent="MyBrowser" time=7 status=200 method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.747 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks request_id=cmghyf1jd7g6fr1xakrzgr7xgr user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.754 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks request_id=cmghyf1jd7g6fr1xakrzgr7xgr user_agent="MyBrowser" time=7 status=200 method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.769 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId request_id=t3b5r6a3jfg57kyqrpa3gdj6dh user_agent="MyBrowser" method=GET plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.776 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks time=7 user_id=myUserId request_id=t3b5r6a3jfg57kyqrpa3gdj6dh user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" status=200 plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.846 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks request_id=7q3frustp78xtqc8osaw3c46wh user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.846 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks user_id=myUserId request_id=qpcmhd4q9j81zy9meobtonw5bw user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.852 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks time=7 method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId request_id=7q3frustp78xtqc8osaw3c46wh user_agent="MyBrowser" status=200 plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.852 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" time=6 status=200 user_id=myUserId request_id=qpcmhd4q9j81zy9meobtonw5bw plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.914 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId request_id=n15m8nz3bfncpce5uh9jtstirc user_agent="MyBrowser" method=GET plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.920 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks status=200 request_id=n15m8nz3bfncpce5uh9jtstirc user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId time=6 plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:25.985 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks request_id=b65w6xpi83d7fr8g14kicqr4yo user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:25.992 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks status=200 method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId request_id=b65w6xpi83d7fr8g14kicqr4yo user_agent="MyBrowser" time=7 plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:26.045 Z] Received HTTP request caller="app/plugin_api.go:970" plugin_id=playbooks request_id=7hk6dr7z7ffutqcrrr78pq9nea user_agent="MyBrowser" method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:44"
debug [2023-07-13 17:45:26.052 Z] Handled HTTP request  caller="app/plugin_api.go:970" plugin_id=playbooks method=GET url="/api/v0/actions/channels/myChannelId?trigger_type=new_member_joins" user_id=myUserId request_id=7hk6dr7z7ffutqcrrr78pq9nea user_agent="MyBrowser" time=7 status=200 plugin_caller="github.com/mattermost/mattermost-plugin-playbooks/server/api/logger.go:57"
debug [2023-07-13 17:45:26.450 Z] websocket.NextReader: client side closed socket caller="platform/web_conn.go:845" user_id=myUserId
debug [2023-07-13 17:45:26.450 Z] Received HTTP request caller="web/handlers.go:163" method=GET url=/api/v4/websocket request_id=ybhab4miafgstboc5fq8cjefcw
debug [2023-07-13 17:45:26.584 Z] inactive connection found for webconn, reusing caller="app/plugin_api.go:970" plugin_id=focalboard webConnID=q8eqzgsbkpg78dck5hqx6agqir userID=myUserId
```

**Comment by BigMakCode** [comment]
![image](https://github.com/mattermost/mattermost/assets/81349914/c02fa8d1-752a-4dde-8697-36f58de281b8)

**Comment by BigMakCode** [comment]
@amyblais 

![image](https://github.com/mattermost/mattermost/assets/81349914/45f84052-6129-4282-9c25-a960866b74e0)

![image](https://github.com/mattermost/mattermost/assets/81349914/864249e2-2f4a-4ece-9777-f8c81cca60e4)

**Comment by amyblais** [comment]
QA was able to reproduce it - opened https://mattermost.atlassian.net/browse/MM-53665.
