### ISSUE TITLE
Invalid Memory Address or nil pointer dereference

### ISSUE THREAD

**Issue by TokkCorp** [mattermost/mattermost#24052]
#### Summary
After updating Mattermost from Version 7.11 to 8.0 the webinterface isn't loading anymore and the mattermost logs display an error.
	
Mobile app is still working as intended.

#### Steps to reproduce
Error is showing after Upgrading to the newest version

#### Expected behavior
web  interface should load 

#### Observed behavior (that appears unintentional) 
Error in the mattermost logs once per connection: 

```
{"timestamp":"2023-07-18 11:44:03.710 +02:00","level":"error","msg":"http: panic serving 127.0.0.1:57132: runtime error: invalid memory address or nil pointer dereference
goroutine 399477 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1854 +0xbf
panic({0x564d6c35af00, 0x564d6d920ce0})
	runtime/panic.go:890 +0x263
github.com/mattermost/mattermost-server/v6/api4.getSelfHostedProducts(0xc005270eb0, {0x564d6c65ce60, 0xc00537b800}, 0xc0021476a8?)
	github.com/mattermost/mattermost-server/v6/api4/cloud.go:312 +0x60
github.com/mattermost/mattermost-server/v6/web.Handler.ServeHTTP({0xc0000f2380, 0x564d6c640e18, {0x564d6cc4a1a7, 0x15}, 0x1, 0x0, 0x0, 0x0, 0x1, 0x0, ...}, ...)
	github.com/mattermost/mattermost-server/v6/web/handlers.go:363 +0x33ca
github.com/mattermost/gziphandler.GzipHandlerWithOpts.func1.1({0x564d6c65e390, 0xc0001f2c40}, 0xc00883ab10?)
	github.com/mattermost/gziphandler@v0.0.1/gzip.go:337 +0x24e
net/http.HandlerFunc.ServeHTTP(0xc002aba700?, {0x564d6c65e390?, 0xc0001f2c40?}, 0x17b38e4c270a5?)
	net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000540, {0x564d6c65e390, 0xc0001f2c40}, 0xc002aba600)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc001c61860?}, {0x564d6c65e390, 0xc0001f2c40}, 0xc002aba600)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc005978990, {0x564d6c65fc80, 0xc0062e93e0})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed","caller":"log/log.go:194","source":"httpserver"}
```

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by TokkCorp** [comment]
Error seems to have fixed itself after 10 minutes or so. Sorry
