### ISSUE TITLE
Failed to instantiate WebSocketClient in a node.js

### ISSUE THREAD

**Issue by BenClaveau** [mattermost/mattermost#26306]
1. Steps to reproduce
```javascript
import mattermost from "@mattermost/client";

const client = new mattermost.WebSocketClient();
client.initialize(`https://${process.env.HOST}/api/v4/websocket`, process.env.TOKEN);
client.addMessageListener(message => {
    console.log(message);
});
```
The stack trace
```bash
.nvm/versions/node/v18.15.0/bin/node ./dist/server.mjs
websocket connecting
Uncaught ReferenceError ReferenceError: WebSocket is not defined
    at initialize (node_modules/@mattermost/client/lib/websocket.js:79:25)
    at <anonymous> (src/server.mts:4:8)
    at run (internal/modules/esm/module_job:194:25)
    --- await ---
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:23:47)
Process exited with code 1
```

2. Expected behavior
for nodejs:
```javascript
import WebSocket from "ws";
```

3. Observed behavior
I've got: Uncaught ReferenceError ReferenceError: WebSocket is not defined in node_modules/@mattermost/client/lib/websocket.js:79:25

You should import it via 'ws'

4. Mattermost server version
9.3.0

5. OS and version
macOS: 14.2.1

6. Any server log errors
No

**Comment by BenoitClaveau** [comment]
Hi Amy,

Here is the information you need:
1. Steps to reproduce
```javascript
import mattermost from "@mattermost/client";

const client = new mattermost.WebSocketClient();
client.initialize(`https://${process.env.HOST}/api/v4/websocket`, process.env.TOKEN);
client.addMessageListener(message => {
    console.log(message);
});
```
The stack trace
```bash
.nvm/versions/node/v18.15.0/bin/node ./dist/server.mjs
websocket connecting
Uncaught ReferenceError ReferenceError: WebSocket is not defined
    at initialize (node_modules/@mattermost/client/lib/websocket.js:79:25)
    at <anonymous> (src/server.mts:4:8)
    at run (internal/modules/esm/module_job:194:25)
    --- await ---
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:23:47)
Process exited with code 1
```
3. Expected behavior

for nodejs:
```javascript
import WebSocket from "ws";
```

5. Observed behavior
6. Mattermost server version
9.3.0
8. OS and version
macOS: 14.2.1
10. Any server log errors
No

**Comment by hmhealey** [comment]
Thanks for the report, @BenoitClaveau. I looked at an old version of the documentation that we had, and we used to have steps that involved setting `global.WebSocket` before instantiating the WS client when using Node.js. [Here's a link to the old docs](https://github.com/mattermost/mattermost-redux?tab=readme-ov-file#nodejs-usage) if you're curious, but is what you'll need:
```js
import mattermost from '@mattermost/client';
import WebSocket from 'ws';

if (!global.WebSocket) {
    global.WebSocket = WebSocket;
}

const client = new mattermost.WebSocketClient();
client.initialize(`https://${process.env.HOST}/api/v4/websocket`, process.env.TOKEN);
client.addMessageListener(message => {
    console.log(message);
});
```

We can definitely re-add those docs to the package, but I want to see if there's a good way to package this so that that's not necessary in the future.

**Comment by BenoitClaveau** [comment]
Thanks,

Here is an example with dynamic import (esm):

```javascript
if (!globalThis.WebSocket) {
    const { WebSocket } = await import("ws");
    globalThis.WebSocket = WebSocket as typeof globalThis.WebSocket;
}
```

**Comment by einarpersson** [comment]
Thanks, I also stumbled on this.

Regardless of the solution, I would recommend adding a brief Websocket example to the client README.

Also btw note that there is currently a typo in the README

```
const client = new Client4();
client4.setUrl('https://mymattermostserver.example.com');
```

client =! client4
