### ISSUE TITLE
"Please use the JavaScript console to capture and report the error"

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/mattermost#27300]
As requested by a red banner in the mattermost OSX desktop app, here's the full console log:

This happened after pressing undo (apple-z) while typing an emoji name.

```
/chat/:1 Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/vc733d5f01de84e3792a4035cd15c58a81717452547180' because it violates the following Content Security Policy directive: "script-src 'self' cdn.rudderlabs.com js.stripe.com/v3 'sha256-ONrd52qEmLJ6ra3JM71gigPm7cHp4qtKuHm9F0ASdyw='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

/chat/:1 Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/vc733d5f01de84e3792a4035cd15c58a81717452547180' because it violates the following Content Security Policy directive: "script-src 'self' cdn.rudderlabs.com/ js.stripe.com/v3 'sha256-ONrd52qEmLJ6ra3JM71gigPm7cHp4qtKuHm9F0ASdyw='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

VM5:2 New API preload initialized
index.js:150 Loading plugin playbooks, version 1.39.3
index.js:150 Loading plugin focalboard, version 7.10.6
index.js:150 Loading plugin com.github.matterpoll.matterpoll, version 1.6.1
index.js:136 Loaded plugin playbooks, version 1.39.3
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810033.66] OctoClient baseURL: https://radiopaedia.org/chat/plugins/focalboard
index.js:136 Loaded plugin focalboard, version 7.10.6
index.js:136 Loaded plugin com.github.matterpoll.matterpoll, version 1.6.1
websocket_actions.jsx:141 Initializing or re-initializing WebSocket
websocket.js:74 websocket connecting to wss://radiopaedia.org/chat/api/v4/websocket
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810033.83] WSClient initialised for plugin id "focalboard"
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810033.84] Unable to find team in store. TeamID: x3zs7ykkobbr9f8c7uqdkw19rw
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810033.84] First component subscribing to team x3zs7ykkobbr9f8c7uqdkw19rw
Metropolis-SemiBold.woff2:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
Metropolis-SemiBoldItalic.woff2:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/plugins/com.github.matterpoll.matterpoll/api/v1/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
com.github.matterpoll.matterpoll_933bad2bc185845b_bundle.js:18 Uncaught (in promise) Error: {"status":404,"error":"Not Found"}
    at y.<anonymous> (com.github.matterpoll.matterpoll_933bad2bc185845b_bundle.js:18:82779)
    at r.emit (com.github.matterpoll.matterpoll_933bad2bc185845b_bundle.js:295:232726)
    at t.onreadystatechange (com.github.matterpoll.matterpoll_933bad2bc185845b_bundle.js:18:86637)
/chat/api/v4/cloud/subscription/self-serve-status:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810034.79] WSClient in plugin mode, reusing Mattermost WS connection
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810034.79] Sending commands for the registered subscriptions
websocket.js:144 got connection id  jpiwgjc87jbnurkafb1auzhgia
focalboard_26cf8858a6f871f9_bundle.js:2 [1717810035.42] Cloud limits: cards=0   views=0
/chat/plugins/com.mattermost.apps/api/v1/bindings?channel_id=og5k9qse1brfxpgo154xg3wy3o&team_id=x3zs7ykkobbr9f8c7uqdkw19rw&user_agent=webapp:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
2@istvan-szmozsanszky:1 Uncaught (in promise) Error: Error invoking remote method 'notify_mention': TypeError: FocusStatus access not authorized, status: 2
/chat/dev/channels/dev-chatter:1 Uncaught (in promise) Error: Error invoking remote method 'notify_mention': TypeError: FocusStatus access not authorized, status: 2
team_controller.tsx:69 computer woke up - reconnecting
websocket_actions.jsx:214 Reconnecting WebSocket
/chat/plugins/com.mattermost.apps/api/v1/bindings?channel_id=hww6fki1bt8ybemcpk5eu8k9dr&team_id=x3zs7ykkobbr9f8c7uqdkw19rw&user_agent=webapp:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/chat/plugins/com.mattermost.apps/api/v1/bindings?channel_id=qdffapaugidpjgixqqzih8hz3y&team_id=x3zs7ykkobbr9f8c7uqdkw19rw&user_agent=webapp:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
team_controller.tsx:69 computer woke up - reconnecting
websocket_actions.jsx:214 Reconnecting WebSocket
/chat/plugins/com.mattermost.apps/api/v1/bindings?channel_id=hww6fki1bt8ybemcpk5eu8k9dr&team_id=x3zs7ykkobbr9f8c7uqdkw19rw&user_agent=webapp:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/chat/plugins/com.mattermost.apps/api/v1/bindings?channel_id=qdffapaugidpjgixqqzih8hz3y&team_id=x3zs7ykkobbr9f8c7uqdkw19rw&user_agent=webapp:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:3404 [Util] handleError::  Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 5 is larger than the node's length (4).
focalboard_26cf8858a6f871f9_bundle.js:2 [Util] handleError::  Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 5 is larger than the node's length (4).
utils.tsx:707 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 5 is larger than the node's length (4).
    at https://radiopaedia.org/chat/static/1490.03898d6a9ba4ef273b7d.js:1:1531058
    at Object.re (https://radiopaedia.org/chat/static/1490.03898d6a9ba4ef273b7d.js:1:1531357)
    at A.nonDebouncedPretextChanged (https://radiopaedia.org/chat/static/8055.c2e8394446fd4bca58d8.js:1:2988522)
    at https://radiopaedia.org/chat/static/8055.c2e8394446fd4bca58d8.js:1:2988788
```

**Comment by amyblais** [comment]
Hi @DanielHeath,

1. What OS version are you on?
2. What Mattermost server version are you on?
3. Are you able to reproduce this at https://community.mattermost.com/?
4. What Mattermost desktop app version are you on?
5. Do you see this issue also on webapp?

**Comment by DanielHeath** [comment]
Sonoma 14.5 (23F79)

Mattermost Version: 9.7.4
Database Schema Version: 119
Build Number: 9004119441
Database: postgres

Desktop app Version 5.8.0 (90825715281)

**Comment by amyblais** [comment]
Thank you, I haven't been able to reproduce it, so it would be helpful if you're able to help test it at https://community.mattermost.com/ (this is on the latest Mattermost server version).

**Comment by amyblais** [comment]
Closing for now. Please re-open this issue if you are able to provide more details on reproduction steps, or if you're able to reproduce this on the community server.
