### ISSUE TITLE
Bulk import failing without clear indications as to why

### ISSUE THREAD

**Issue by Achder** [mattermost/mattermost#27972]
#### Summary

I'm trying to migrate from one self-hosted instance to another.
I exported the data from the existing instance, downloaded the file to the new server and tried to import the file in local mode.

#### Steps to reproduce

1. Updated existing instance to the latest version
2. Setup new instance on a different server with the same version
3. Logged in to the new server
4. Used mmctl to authenticate on the old instance
5. Created an export including profile-pictures
6. Downloaded the export file
7. Trying to import the file using:

```
mmctl import process --bypass-upload do5683zbm3815gxujrpwru8fbc_export.zip --local
```

The job is pending for a few seconds, then I get this:

```
  ID: wsfgofwy5tfo9k69s6ei881uar
  Status: error
  Created: 2024-08-14 12:21:35 +0000 UTC
  Started: 2024-08-14 12:21:50 +0000 UTC
  Data: map[error:Unable to update the job. extract_content:true import_file:/root/do5683zbm3815gxujrpwru8fbc_export.zip local_mode:true]
```

#### Operating System

Ubuntu 22.04.4 LTS

#### Mattermost Server Version

Mattermost Version: 9.10.1

#### Expected behavior

The file should either be imported or throw a clear error message.

#### Observed behavior

The import job fails. The errors in journalctl are unclear.

#### Log Output

Looking a journalctl I get endless go issues until the service is restarted:

```
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/hashicorp/go-plugin.(*Client).logStderr(0xc001357900, {0xc004983680?, 0xc0049890e0?}, {0x35ac9c0?, 0xc007d1c318?})
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/hashicorp/go-plugin@v1.6.0/client.go:1170 +0x2b5 fp=0xc007ce6fa8 sp=0xc007ce6da8 pc=0xac3235
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/hashicorp/go-plugin.(*Client).Start.func6()
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/hashicorp/go-plugin@v1.6.0/client.go:761 +0x30 fp=0xc007ce6fe0 sp=0xc007ce6fa8 pc=0xac1c70
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc007ce6fe8 sp=0xc007ce6fe0 pc=0x474301
Aug 14 12:21:51 mattermost mattermost[565603]: created by github.com/hashicorp/go-plugin.(*Client).Start in goroutine 451
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/hashicorp/go-plugin@v1.6.0/client.go:761 +0x19e5
Aug 14 12:21:51 mattermost mattermost[565603]: goroutine 433 [select]:
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.gopark(0xc002398f88?, 0x2?, 0x7d?, 0x25?, 0xc002398f54?)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/proc.go:398 +0xce fp=0xc002398de8 sp=0xc002398dc8 pc=0x440a8e
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.selectgo(0xc002398f88, 0xc002398f50, 0x0?, 0x0, 0x0?, 0x1)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/select.go:327 +0x725 fp=0xc002398f08 sp=0xc002398de8 pc=0x4511a5
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/mattermost/mattermost/server/public/plugin.(*PluginHealthCheckJob).run(0xc004ff9ae0)
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/plugin/health_check.go:38 +0x112 fp=0xc002398fc8 sp=0xc002398f08 pc=0xc99b12
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/mattermost/mattermost/server/public/plugin.(*Environment).TogglePluginHealthCheckJob.func1()
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/plugin/environment.go:665 +0x25 fp=0xc002398fe0 sp=0xc002398fc8 pc=0xc98845
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc002398fe8 sp=0xc002398fe0 pc=0x474301
Aug 14 12:21:51 mattermost mattermost[565603]: created by github.com/mattermost/mattermost/server/public/plugin.(*Environment).TogglePluginHealthCheckJob in goroutine 1
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/plugin/environment.go:665 +0x23f
Aug 14 12:21:51 mattermost mattermost[565603]: goroutine 416 [select]:
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.gopark(0xc00239af90?, 0x3?, 0x7d?, 0x25?, 0xc00239af3a?)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/proc.go:398 +0xce fp=0xc00239adb0 sp=0xc00239ad90 pc=0x440a8e
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.selectgo(0xc00239af90, 0xc00239af34, 0x35d1bc0?, 0x0, 0x35d1bc0?, 0x1)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/select.go:327 +0x725 fp=0xc00239aed0 sp=0xc00239adb0 pc=0x4511a5
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/mattermost/mattermost/server/public/model.createTask.func1()
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/model/scheduled_task.go:69 +0x205 fp=0xc00239afe0 sp=0xc00239aed0 pc=0xba0245
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc00239afe8 sp=0xc00239afe0 pc=0x474301
Aug 14 12:21:51 mattermost mattermost[565603]: created by github.com/mattermost/mattermost/server/public/model.createTask in goroutine 181
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/model/scheduled_task.go:46 +0x165
Aug 14 12:21:51 mattermost mattermost[565603]: goroutine 592 [chan receive]:
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.gopark(0x0?, 0x7c725d?, 0x1?, 0x75?, 0x20000005ac9e0?)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/proc.go:398 +0xce fp=0xc0022a9ee8 sp=0xc0022a9ec8 pc=0x440a8e
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.chanrecv(0xc007d24480, 0xc0022a9fa8, 0x1)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/chan.go:583 +0x3cd fp=0xc0022a9f60 sp=0xc0022a9ee8 pc=0x40ba2d
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.chanrecv2(0xc0022a9fd0?, 0x7c7038?)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/chan.go:447 +0x12 fp=0xc0022a9f88 sp=0xc0022a9f60 pc=0x40b652
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/hashicorp/go-plugin.(*Client).Start.func4.1()
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/hashicorp/go-plugin@v1.6.0/client.go:816 +0x77 fp=0xc0022a9fe0 sp=0xc0022a9f88 pc=0xac12b7
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc0022a9fe8 sp=0xc0022a9fe0 pc=0x474301
Aug 14 12:21:51 mattermost mattermost[565603]: created by github.com/hashicorp/go-plugin.(*Client).Start.func4 in goroutine 453
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/hashicorp/go-plugin@v1.6.0/client.go:814 +0x6e
Aug 14 12:21:51 mattermost mattermost[565603]: goroutine 558 [select]:
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.gopark(0xc00239bf90?, 0x3?, 0x25?, 0x24?, 0xc00239bf3a?)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/proc.go:398 +0xce fp=0xc00239bdb0 sp=0xc00239bd90 pc=0x440a8e
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.selectgo(0xc00239bf90, 0xc00239bf34, 0xc00239beb8?, 0x0, 0x7c725d?, 0x1)
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/select.go:327 +0x725 fp=0xc00239bed0 sp=0xc00239bdb0 pc=0x4511a5
Aug 14 12:21:51 mattermost mattermost[565603]: github.com/mattermost/mattermost/server/public/model.createTask.func1()
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/model/scheduled_task.go:69 +0x205 fp=0xc00239bfe0 sp=0xc00239bed0 pc=0xba0245
Aug 14 12:21:51 mattermost mattermost[565603]: runtime.goexit()
Aug 14 12:21:51 mattermost mattermost[565603]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc00239bfe8 sp=0xc00239bfe0 pc=0x474301
Aug 14 12:21:51 mattermost mattermost[565603]: created by github.com/mattermost/mattermost/server/public/model.createTask in goroutine 180
Aug 14 12:21:51 mattermost mattermost[565603]:         github.com/mattermost/mattermost/server/public/model/scheduled_task.go:46 +0x165
```

#### Additional Information

I'm using postgresql v14.12
I tested my postgres connection string using `pg_isready -d 'my-connection-string'` which returns with exit code 0, indicating the connection string is ok.

Do I need to further prepare the instance?
I have installed mattermost and postgres. 
I have set the postgres connection string in the config and activated local-mode. 

That's basically all I did before trying to import.

**Comment by agnivade** [comment]
@Achder - could you please upload your entire mattermost.log file? Thanks. We need to look at the full log output.
