### ISSUE TITLE
Crash when downloading an image (`TypeError: s.nativeImage.createThumbnailFromPath is not a function`)

### ISSUE THREAD

**Issue by SimonWoidig** [mattermost/mattermost#29312]
#### Summary

Mattermost crashes when trying to download an image.

#### Steps to reproduce

1. Click on any image in a chat, this opens the thumbnail
2. Click on download in the top right corner
3. See error as Mattermost crashes, the download is cancelled

#### Operating System

Fedora 39 KDE Plasma with Linux kernel 6.11.5-100.fc39.x86_64

#### Mattermost Server Version

Mattermost Version: 10.0.1
Database Schema Version: 125
Build Number: 11258452730

#### Expected behavior

The image downloads without a problem.

#### Observed behavior

Mattermost crashes, download is cancelled

#### Log Output

```
Application: Mattermost 5.9.0
Platform: Linux 6.11.5-100.fc39.x86_64 x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/app/main/resources/app.asar/index.js:2:258218)
    at C.upsertFileToDownloads (/app/main/resources/app.asar/index.js:2:255626)
    at C.doneEventController (/app/main/resources/app.asar/index.js:2:256982)
    at DownloadItem.<anonymous> (/app/main/resources/app.asar/index.js:2:254788)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
```

#### Additional Information

Search through Jira returned this ticket: https://mattermost.atlassian.net/issues/MM-60232
The ticket is for an older version and the bug seems a bit different aswell

Image of the crash: ![image](https://github.com/user-attachments/assets/a03d39b0-4387-4c20-80b6-bcff7ef7683b)

**Comment by amyblais** [comment]
@SimonWoidig @n4zgu1 I'm not able to reproduce this (on webapp macOS). Are you able to reproduce this on our community server here https://community.mattermost.com/?

**Comment by SimonWoidig** [comment]
> @SimonWoidig @n4zgu1 I'm not able to reproduce this (on webapp macOS). Are you able to reproduce this on our community server here [community.mattermost.com](https://community.mattermost.com/)?

Was able to reproduce after adding the server to the desktop app.
![image](https://github.com/user-attachments/assets/12a9a703-294f-46d2-a72d-5557019303d4)

Log:
```
Application: Mattermost 5.9.0
Platform: Linux 6.11.5-100.fc39.x86_64 x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/app/main/resources/app.asar/index.js:2:258218)
    at C.upsertFileToDownloads (/app/main/resources/app.asar/index.js:2:255626)
    at C.doneEventController (/app/main/resources/app.asar/index.js:2:256982)
    at DownloadItem.<anonymous> (/app/main/resources/app.asar/index.js:2:254788)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
    ```
